### ISSUE TITLE
[Bug] CRUD table footer row looks different then header row

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-coreuiv2#18]
So here's Backpack v5, both header table row and footer table row look identical:

![CleanShot 2023-07-01 at 14 00 42](https://github.com/Laravel-Backpack/theme-coreuiv2/assets/1032474/9fc7eca4-04c6-4ef7-8d57-1f8cdca4eaa1)

But then in Backpack v6, even in CoreUIv2, those DO NOT look the same:

![CleanShot 2023-07-01 at 14 01 41](https://github.com/Laravel-Backpack/theme-coreuiv2/assets/1032474/0fa1ccb1-3ba6-410a-853b-25a4407fa16e)

They should both look like the header row.

**Comment by tabacitu** [comment]
@promatik I remember you fixed this in Tabler... but I see it's a problem in CoreUIv2 and CoreUIv4 too... 

Maybe the problem was upstream, in some ListOperation HTML? And we should fix it there?

**Comment by promatik** [comment]
Fix for this one here; https://github.com/Laravel-Backpack/CRUD/pull/5225
