### ISSUE TITLE
[Bug] Sidebar dropdown does not open when clicking on the title.

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-coreuiv2#24]
# Bug report

### What I did

I noticed that clicking the dropdown title or icon does not open/close the dropdown. 

### What I expected to happen

I expected the dropdown to open/close as happens in Backpack v5.

### What happened

![20230711-1130-52 9802363](https://github.com/Laravel-Backpack/theme-coreuiv2/assets/7188159/5b869391-0477-4d33-9b61-e2568a31d2f3)

Notice that the classes change in html but the dropdown does not open/close when I click in the text.

**Comment by promatik** [comment]
Fix is here; https://github.com/Laravel-Backpack/theme-coreuiv2/pull/27 👌
